### ISSUE TITLE
Comments of a web designer

### ISSUE THREAD

**Issue by phylib** [Felfio/AAUFood#27]
I recently spoke with a designer about or page. The following comments may be discussed in our team:

- Padding below weekday is to small
- The globe icon is not perfect for links, better maybe `fa-external-link`
- The font size of the menucard headers is to small
- The heights of the menucards should be equal (maybe with flexbox)
- The main course should be emphasized
- On saturday and sunday: "Kein Mittagsmenü" and "Tagesempfehlung" should be replaced with a default text with icon like the closed notification. E.g. "Heute leider kein Mittagsmenü" + `fa-frown`

I hope i didn't miss anything.

**Comment by Kruemelkatze** [comment]
Additional points:

- Navigation arrows on desktop **may** be moved to the top, next to the weekday.
- Weekday should be more emphasized, e.g. with a ribbon
- Allergens should be made distinct from the menus, for example by super- or subscript
- The price pills for foods should be vertically centered, so that the text does not underflow the price pill
- Consider 3 columns, with Uniwirt and Uni-Pizzeria stacked in the middle
    - Consider making the resulting three columns equally high.
- Try Bootstrap 4 in flexbox mode

@behackl and me suggest a "Styleathon" somewhen in the next two weeks, where we address these topics together. So there's no need for somebody tackling these on their own. :)

**Comment by phylib** [comment]
+1 for Styleathon

**Comment by behackl** [comment]
Wir sollten uns die hier angeführten Punkte einmal anschauen, entscheiden was davon noch zu erledigen ist, und entsprechende kleinere Issues anlegen. :smile:

**Comment by phylib** [comment]
Wart ma mit der Besprechung bis Semesterbeginn, nächste Woche ist bei mir schon ziemlich voll und übernächste bin ich auf einer Konferenz...
Und dann ist eh schon Oktober ;)

**Comment by Kruemelkatze** [comment]
2-3 years and a redesign later, most points are either implemented (paddings, flexbox, icons, allergens, font sizes), not suitable (same height for cards, 3 columns) or not possible (emphasis on main course). So I think we can finally close this. 😁
